import { createSecretToken, hashToken, verifyToken } from '../../crypto/token-hash';
import type { FlowPassDatabase } from '../../db/connection';
import { v7 as uuidv7 } from 'uuid';
export const ADMIN_SESSION_COOKIE = 'flowpass_admin_session'; export const ADMIN_CSRF_COOKIE = 'flowpass_admin_csrf';
const ADMIN_IDLE_MS = 30 * 60_000;
const ADMIN_ABSOLUTE_MS = 8 * 60 * 60_000;
export function createAdminSession(database: FlowPassDatabase, adminUserId: string, now = new Date()): { token: string; csrf: string; expiresAt: string } { const token = createSecretToken(); const csrf = createSecretToken(); const id = uuidv7(); const issued = now.toISOString(); const absolute = new Date(now.getTime() + ADMIN_ABSOLUTE_MS).toISOString(); const idle = new Date(Math.min(now.getTime() + ADMIN_IDLE_MS, Date.parse(absolute))).toISOString(); database.prepare(`INSERT INTO admin_sessions (id, admin_user_id, token_hash, csrf_secret_hash, issued_at, idle_expires_at, absolute_expires_at, last_seen_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(id, adminUserId, token.hash, csrf.hash, issued, idle, absolute, issued); return { token: token.token, csrf: csrf.token, expiresAt: absolute }; }
export function authenticateAdmin(database: FlowPassDatabase, token: string | null, now = new Date()): { adminId: string; csrfHash: string } | null { if (!token) return null; const row = database.prepare(`SELECT s.admin_user_id, s.token_hash, s.csrf_secret_hash, s.idle_expires_at, s.absolute_expires_at FROM admin_sessions s JOIN admin_users u ON u.id = s.admin_user_id AND u.status = 'active' WHERE s.revoked_at IS NULL AND s.token_hash = ?`).get(hashToken(token)) as { admin_user_id: string; token_hash: string; csrf_secret_hash: string; idle_expires_at: string; absolute_expires_at: string } | undefined; if (!row || Date.parse(row.idle_expires_at) <= now.getTime() || Date.parse(row.absolute_expires_at) <= now.getTime() || !verifyToken(token, row.token_hash)) return null; const nextIdle = new Date(Math.min(now.getTime() + ADMIN_IDLE_MS, Date.parse(row.absolute_expires_at))).toISOString(); database.prepare('UPDATE admin_sessions SET last_seen_at = ?, idle_expires_at = ? WHERE token_hash = ?').run(now.toISOString(), nextIdle, row.token_hash); return { adminId: row.admin_user_id, csrfHash: row.csrf_secret_hash }; }
export function verifyAdminCsrf(csrfToken: string | null, csrfHash: string | null): boolean { if (!csrfToken || !csrfHash) return false; return verifyToken(csrfToken, csrfHash); }
