export const FLOWPASS_SAMPLE = {
  passport_draft: {
    use_case: {
      title: '社團招生影片製作與發布',
      purpose: '使用 AI 工具將社員影像與聲音素材轉換為招生宣傳影片',
      intended_outcome: '產出影片並經確認後於公開社群發布',
    },
    nodes: [
      {
        id: 'node_mat_01',
        kind: 'data',
        label: '社員照片與錄音原始檔',
        data_category: 'photo',
        sensitivity: 'high',
        source_field: 'materials',
        source_excerpt: '社員照片與錄音',
        confidence: 1,
        needs_confirmation: false,
      },
      {
        id: 'node_mat_02',
        kind: 'data',
        label: '社員錄音原始檔',
        data_category: 'audio',
        sensitivity: 'high',
        source_field: 'materials',
        source_excerpt: '社員照片與錄音',
        confidence: 1,
        needs_confirmation: false,
      },
      {
        id: 'node_tool_01',
        kind: 'ai_tool',
        label: 'AI 影片生成工具',
        data_category: 'other',
        sensitivity: 'medium',
        source_field: 'intended_use',
        source_excerpt: '使用 AI 影片生成工具製作社團招生影片',
        confidence: 0.9,
        needs_confirmation: true,
      },
      {
        id: 'node_data_pii_01',
        kind: 'data',
        label: '人臉生物特徵資料',
        data_category: 'personal_data',
        sensitivity: 'high',
        source_field: 'personal_or_sensitive_data',
        source_excerpt: '人臉、姓名、名牌、聲音與可能提及的聯絡資訊',
        confidence: 1,
        needs_confirmation: false,
      },
      {
        id: 'node_data_pii_02',
        kind: 'data',
        label: '聲音生物特徵與聯絡資訊',
        data_category: 'personal_data',
        sensitivity: 'high',
        source_field: 'personal_or_sensitive_data',
        source_excerpt: '人臉、姓名、名牌、聲音與可能提及的聯絡資訊',
        confidence: 1,
        needs_confirmation: false,
      },
      {
        id: 'node_storage_01',
        kind: 'storage',
        label: '限定成員雲端資料夾',
        data_category: 'other',
        sensitivity: 'medium',
        source_field: 'destination_and_audience',
        source_excerpt: '先放在限定成員的雲端資料夾',
        confidence: 0.95,
        needs_confirmation: true,
      },
      {
        id: 'node_dest_01',
        kind: 'destination',
        label: '公開社群平台',
        data_category: 'other',
        sensitivity: 'low',
        source_field: 'destination_and_audience',
        source_excerpt: '發布到公開社群',
        confidence: 0.95,
        needs_confirmation: true,
      },
      {
        id: 'node_org_01',
        kind: 'organization',
        label: '社團組織',
        data_category: 'other',
        sensitivity: 'low',
        source_field: 'destination_and_audience',
        source_excerpt: '經社團確認後',
        confidence: 0.8,
        needs_confirmation: true,
      },
    ],
    edges: [
      {
        id: 'edge_01',
        from_node_id: 'node_mat_01',
        to_node_id: 'node_tool_01',
        purpose: '提供照片素材供 AI 生成影片',
        source_field: 'intended_use',
        source_excerpt: '使用 AI 影片生成工具製作社團招生影片',
        confidence: 0.9,
        needs_confirmation: true,
      },
      {
        id: 'edge_02',
        from_node_id: 'node_mat_02',
        to_node_id: 'node_tool_01',
        purpose: '提供錄音素材供 AI 生成影片',
        source_field: 'intended_use',
        source_excerpt: '使用 AI 影片生成工具製作社團招生影片',
        confidence: 0.9,
        needs_confirmation: true,
      },
      {
        id: 'edge_03',
        from_node_id: 'node_tool_01',
        to_node_id: 'node_storage_01',
        purpose: '儲存生成的影片草稿以供內部審核',
        source_field: 'destination_and_audience',
        source_excerpt: '先放在限定成員的雲端資料夾',
        confidence: 0.9,
        needs_confirmation: true,
      },
      {
        id: 'edge_04',
        from_node_id: 'node_storage_01',
        to_node_id: 'node_dest_01',
        purpose: '經確認後發布至公開平台',
        source_field: 'destination_and_audience',
        source_excerpt: '經社團確認後發布到公開社群',
        confidence: 0.9,
        needs_confirmation: true,
      },
    ],
    sharing_scope: {
      audience: 'public',
      source_field: 'destination_and_audience',
      source_excerpt: '發布到公開社群',
      needs_confirmation: true,
    },
    retention: {
      storage_location: 'node_storage_01',
      duration: 'unknown',
      deletion_plan: 'unknown',
      needs_confirmation: true,
    },
    safety_actions: [
      {
        id: 'action_01',
        action: '取得所有出鏡社員之書面肖像權與聲音使用同意書',
        reason:
          '涉及人臉與聲音等高度敏感個人生物特徵資料，且最終用途為公開發布',
        applies_to_node_ids: [
          'node_data_pii_01',
          'node_data_pii_02',
          'node_dest_01',
        ],
        status: 'required_confirmation',
        evidence_type: 'applicant_confirmation',
      },
      {
        id: 'action_02',
        action: '檢查並模糊化影片中可能出現的名牌或背景聯絡資訊',
        reason: '防止非預期之個人聯絡資訊洩漏',
        applies_to_node_ids: ['node_data_pii_02', 'node_tool_01'],
        status: 'required_confirmation',
        evidence_type: 'applicant_confirmation',
      },
      {
        id: 'action_03',
        action: '確認 AI 工具服務條款中關於上傳資料是否用於模型訓練',
        reason: '確保社員隱私資料未被用於第三方模型訓練',
        applies_to_node_ids: ['node_tool_01'],
        status: 'required_confirmation',
        evidence_type: 'system_check',
      },
      {
        id: 'action_04',
        action: '設定雲端資料夾存取權限僅限社團核心成員',
        reason: '在公開發布前限制敏感草稿的存取範圍',
        applies_to_node_ids: ['node_storage_01'],
        status: 'required_confirmation',
        evidence_type: 'applicant_confirmation',
      },
    ],
    confirmation_questions: [
      {
        id: 'q_01',
        question: '請指定具體使用的「AI 影片生成工具」名稱與供應商？',
        reason: '不同工具的隱私政策與資料處理方式差異巨大，影響合規性評估',
        related_node_ids: ['node_tool_01'],
        priority: 'high',
      },
      {
        id: 'q_02',
        question:
          '是否已獲得所有出現在照片與錄音中的社員明確書面同意，允許其生物特徵用於公開宣傳？',
        reason: '涉及個資法與肖像權，缺乏同意將導致嚴重法律風險',
        related_node_ids: [
          'node_data_pii_01',
          'node_data_pii_02',
          'node_dest_01',
        ],
        priority: 'high',
      },
      {
        id: 'q_03',
        question: '雲端資料夾的具体平台為何（如 Google Drive, Dropbox）？',
        reason: '不同平台的預設安全性與資料駐地不同',
        related_node_ids: ['node_storage_01'],
        priority: 'medium',
      },
      {
        id: 'q_04',
        question: '公開社群平台具體指哪些（如 Facebook, Instagram, YouTube）？',
        reason: '各平台對 AI 生成內容有不同標註要求',
        related_node_ids: ['node_dest_01'],
        priority: 'medium',
      },
      {
        id: 'q_05',
        question:
          '影片發布後，原始素材與中間生成檔預計保留多久？是否有刪除計畫？',
        reason: '符合資料最小化與保留原則',
        related_node_ids: [
          'node_mat_01',
          'node_mat_02',
          'node_storage_01',
        ],
        priority: 'medium',
      },
      {
        id: 'q_06',
        question: 'AI 工具是否啟用了任何第三方插件或擴充功能？',
        reason: '插件可能擁有獨立的資料存取權限',
        related_node_ids: ['node_tool_01'],
        priority: 'medium',
      },
      {
        id: 'q_07',
        question:
          '影片中是否包含未滿 18 歲之社員？若有，是否取得法定代理人同意？',
        reason: '未成年人個資保護有更嚴格的法律要求',
        related_node_ids: ['node_data_pii_01', 'node_data_pii_02'],
        priority: 'high',
      },
      {
        id: 'q_08',
        question: '「社團確認」的具體流程為何？由誰負責最終審核？',
        reason: '明確責任歸屬以進行內部控管',
        related_node_ids: ['node_org_01'],
        priority: 'low',
      },
    ],
    administrative_hints: {
      requested_tool: 'unknown',
      invoice_fields_required: [
        'tool_name',
        'purchase_date',
        'amount',
        'invoice_number',
      ],
      subsidy_calculation: 'not_performed_by_ai',
      requires_officer_review: true,
    },
    audit: {
      draft_status: 'ai_generated_unconfirmed',
      rules_version: 'hackathon-mvp-2026-08-27',
      unknown_fields: [
        '$.retention.duration',
        '$.retention.deletion_plan',
        '$.administrative_hints.requested_tool',
      ],
    },
  },
} as const;

export const FLOWPASS_SAMPLE_JSON = JSON.stringify(FLOWPASS_SAMPLE, null, 2);
