import { z } from 'zod';
import { v7 as uuidv7 } from 'uuid';
import { ApiErrorCode, apiFailure, apiSuccess, parseQuotedEtag, toJsonResponse } from '../../../../../../../shared/api-contract';
import { getPublicRuntime } from '../../../../../../../server/public/runtime';
import { deleteApplicantMutationReservation, finalizeApplicantMutation, isValidMutationKey, readApplicantMutation, reserveApplicantMutation } from '../../../../../../../server/public/public-mutations';
import { encryptDatabaseText } from '../../../../../../../server/db/repositories/encrypted-fields';
import { appendEncryptedAuditLog } from '../../../../../../../server/db/repositories/audit';
const BodySchema = z.object({ value: z.string().min(1).max(4096) }).strict();
function cookie(request: Request, name: string): string | null { for (const part of (request.headers.get('cookie') ?? '').split(';')) { const [key, ...value] = part.trim().split('='); if (key === name) return value.join('=') || null; } return null; }
export async function PATCH(request: Request, context: { params: Promise<{ caseId: string; fieldId: string }> }): Promise<Response> {
  const runtime = getPublicRuntime(); const requestId = runtime?.requestIdGenerator?.() ?? crypto.randomUUID();
  if (!runtime) return toJsonResponse(apiFailure(ApiErrorCode.DEPENDENCY_UNAVAILABLE, requestId));
  if (!runtime.lineSessions.isPublicOrigin(request.headers.get('origin'))) return toJsonResponse(apiFailure(ApiErrorCode.CSRF_FAILED, requestId));
  const sessionToken = cookie(request, 'flowpass_session'); const csrf = runtime.lineSessions.verifyApplicantCsrf({ sessionToken, csrfCookie: cookie(request, 'flowpass_csrf'), csrfHeader: request.headers.get('x-flowpass-csrf') });
  const key = request.headers.get('idempotency-key'); const expected = parseQuotedEtag(request.headers.get('if-match')); if (!csrf) return toJsonResponse(apiFailure(ApiErrorCode.CSRF_FAILED, requestId)); if (!isValidMutationKey(key) || expected === null) return toJsonResponse(apiFailure(ApiErrorCode.INVALID_REQUEST, requestId));
  let body: unknown; try { body = await request.json(); } catch { return toJsonResponse(apiFailure(ApiErrorCode.INVALID_REQUEST, requestId)); } const parsed = BodySchema.safeParse(body); if (!parsed.success) return toJsonResponse(apiFailure(ApiErrorCode.INVALID_REQUEST, requestId));
  const { caseId, fieldId } = await context.params; const now = runtime.clock?.() ?? new Date(); const route = `/api/v1/cases/${caseId}/document-fields/${fieldId}`; const projection = { caseId, fieldId, value: parsed.data.value, ifMatch: request.headers.get('if-match') };
  const existing = readApplicantMutation({ database: runtime.database, crypto: runtime.crypto, applicantId: csrf.applicantId, method: 'PATCH', normalizedRoute: route, idempotencyKey: key, requestProjection: projection, now }); if (existing?.kind === 'conflict') return toJsonResponse(apiFailure(ApiErrorCode.IDEMPOTENCY_KEY_REUSED, requestId)); if (existing?.kind === 'replay') return toJsonResponse(JSON.parse(existing.body), { status: existing.status });
  const reservation = reserveApplicantMutation({ database: runtime.database, crypto: runtime.crypto, applicantId: csrf.applicantId, method: 'PATCH', normalizedRoute: route, idempotencyKey: key, requestProjection: projection, now }); if (reservation.kind !== 'reserved') return toJsonResponse(apiFailure(reservation.kind === 'conflict' ? ApiErrorCode.IDEMPOTENCY_KEY_REUSED : ApiErrorCode.DEPENDENCY_UNAVAILABLE, requestId));
  try {
    const result = runtime.database.transaction(() => {
      const row = runtime.database.prepare(`SELECT c.row_version, c.state, d.id AS document_id, d.status AS document_status FROM documents d JOIN cases c ON c.id = d.case_id JOIN document_fields f ON f.document_id = d.id WHERE d.case_id = ? AND f.id = ? AND c.applicant_id = ?`).get(caseId, fieldId, csrf.applicantId) as { row_version: number; state: string; document_id: string; document_status: string } | undefined;
      if (!row) throw new Error('NOT_FOUND'); if (row.row_version !== expected) throw new Error('ETAG_MISMATCH');
      if (!['draft', 'awaiting_documents', 'returned_for_correction'].includes(row.state) || row.document_status === 'deleted') throw new Error('INVALID_STATE');
      const reviewId = uuidv7(); runtime.database.prepare(`INSERT INTO document_field_reviews (id, document_field_id, review_kind, value_enc, value_hmac, decision, reason_enc, actor_type, actor_id, created_at) VALUES (?, ?, 'applicant_correction', ?, ?, 'corrected', NULL, 'applicant', ?, ?)`).run(reviewId, fieldId, encryptDatabaseText(runtime.crypto, 'document_field_reviews', 'value_enc', reviewId, parsed.data.value), runtime.crypto.hmacLookup(parsed.data.value, 'document-field-review-value'), csrf.applicantId, now.toISOString());
      const pointer = runtime.database.prepare('UPDATE document_fields SET effective_review_id = ? WHERE id = ?').run(reviewId, fieldId); if (pointer.changes !== 1) throw new Error('DEPENDENCY_UNAVAILABLE');
      appendEncryptedAuditLog(runtime.database, runtime.crypto, { id: uuidv7(), actorType: 'applicant', actorId: csrf.applicantId, action: 'update', entityType: 'document_field', entityId: fieldId, beforeHash: null, afterHash: runtime.crypto.hmacLookup(parsed.data.value, 'document-field-review-value'), detail: { kind: 'operation', operation: 'update', outcome: 'ok' }, requestId, createdAt: now.toISOString() });
      const changed = runtime.database.prepare('UPDATE cases SET row_version = row_version + 1, updated_at = ? WHERE id = ? AND row_version = ?').run(now.toISOString(), caseId, row.row_version); if (changed.changes !== 1) throw new Error('ETAG_MISMATCH'); return { fieldId, reviewId, rowVersion: row.row_version + 1 };
    })(); const response = apiSuccess(result, requestId, result.rowVersion); finalizeApplicantMutation({ database: runtime.database, crypto: runtime.crypto, reservation, idempotencyKey: key, status: 201, publicBody: JSON.stringify(response), now }); return toJsonResponse(response, { status: 201, headers: { ETag: response.meta.etag ?? '', 'Cache-Control': 'no-store' } });
  } catch (error) { deleteApplicantMutationReservation({ database: runtime.database, crypto: runtime.crypto, reservation, idempotencyKey: key }); const code = error instanceof Error && error.message === 'NOT_FOUND' ? ApiErrorCode.NOT_FOUND : error instanceof Error && error.message === 'ETAG_MISMATCH' ? ApiErrorCode.ETAG_MISMATCH : error instanceof Error && error.message === 'INVALID_STATE' ? ApiErrorCode.INVALID_STATE : ApiErrorCode.DEPENDENCY_UNAVAILABLE; return toJsonResponse(apiFailure(code, requestId)); }
}
