import { createRoot } from 'react-dom/client';
import { useEffect, useState } from 'react';
import './admin.css';
import './review.css';
import { DataManager } from './data-manager';
import { SecurityAlertPublisher } from './security-alert-publisher';
import { api, ApiError } from './api';
import { record, string, sessionOf, caseOf } from './parsers';
import type { Case, Review, ReviewDecision, Session } from './types';
import { uuid } from './format';
import { Login, PasswordChange, Recovery } from './auth-views';
import { Queue } from './queue';
import { Panel } from './case-panel';
import { AiUsagePanel } from './ai-usage-panel';

function App() {
  const [session, setSession] = useState<Session | null>(null), [view, setView] = useState<'login' | 'recovery' | 'password' | 'dashboard' | 'ai-usage' | 'security-incidents'>('login'), [cases, setCases] = useState<Case[]>([]), [selected, setSelected] = useState<Case | null>(null), [managing, setManaging] = useState<Case | null>(null), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [queueError, setQueueError] = useState(''), [authError, setAuthError] = useState(''), [panelError, setPanelError] = useState(''), [notice, setNotice] = useState('');
  const refreshSession = async () => { try { const next = sessionOf(await api<unknown>('/admin/v1/session')); setSession(next); setView(!next.authenticated ? 'login' : next.mustChangePassword ? 'password' : 'dashboard'); return next; } catch (e) { const err = e as ApiError; if (err.status === 401 || err.status === 403) { setSession(null); setView('login'); return null; } setAuthError(err.message); return null; } };
  const load = async () => { setLoading(true); setQueueError(''); try { const data = record(await api<unknown>('/admin/v1/cases')); const next = (Array.isArray(data.cases) ? data.cases : []).map(caseOf).filter((value): value is Case => value !== null); setCases(next); setSelected((old) => old ? next.find((item) => item.id === old.id) ?? null : null); } catch (e) { const err = e as ApiError; if (err.status === 401) { setSession(null); setView('login'); } else setQueueError(err.message || '案件清單暫時無法載入。'); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void refreshSession(); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (view !== 'dashboard' || !session?.authenticated || session.mustChangePassword) return; const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [view, session?.authenticated, session?.mustChangePassword]);
  const login = async (displayName: string, password: string) => { setBusy(true); setAuthError(''); try { await api('/admin/v1/sessions', { method: 'POST', body: JSON.stringify({ displayName, password }) }); const next = await refreshSession(); if (next?.authenticated) setNotice(next.mustChangePassword ? '請先設定新密碼。' : '已登入管理後台。'); } catch (e) { setAuthError((e as ApiError).message || '登入失敗，請確認帳號或密碼。'); } finally { setBusy(false); } };
  const change = async (currentPassword: string, newPassword: string) => { setBusy(true); setAuthError(''); try { await api('/admin/v1/password/change', { method: 'POST', body: JSON.stringify({ currentPassword, newPassword }) }); await refreshSession(); setNotice('密碼已更新；其他登入工作階段已失效。'); } catch (e) { setAuthError((e as ApiError).message); } finally { setBusy(false); } };
  const start = async () => { setBusy(true); setAuthError(''); try { const data = record(await api<unknown>('/admin/v1/password-recovery/start', { method: 'POST', body: '{}' })); return string(data.challengeToken ?? data.token ?? record(data.challenge).token) ?? null; } catch (e) { setAuthError((e as ApiError).message); return null; } finally { setBusy(false); } };
  const complete = async (challengeToken: string, newPassword: string) => { setBusy(true); setAuthError(''); try { await api('/admin/v1/password-recovery/complete', { method: 'POST', body: JSON.stringify({ challengeToken, newPassword }) }); setView('login'); setNotice('密碼已重設，請使用新密碼登入。'); } catch (e) { setAuthError((e as ApiError).message); } finally { setBusy(false); } };
  const logout = async () => { setBusy(true); setAuthError(''); try { await api('/admin/v1/sessions/current', { method: 'DELETE' }); } catch (e) { if ((e as ApiError).status !== 401) setAuthError((e as ApiError).message); } finally { setSession(null); setCases([]); setSelected(null); setManaging(null); setView('login'); setBusy(false); setNotice('已登出管理後台。'); } };
  const update = async (review: Review, decision: ReviewDecision) => { if (!selected) return; setBusy(true); setPanelError(''); const headers: Record<string, string> = { 'idempotency-key': uuid() }; if (selected.rowVersion !== undefined) headers['if-match'] = `"${selected.rowVersion}"`; const body: Record<string, unknown> = { action: review.action, toState: review.toState, ...decision }; try { const data = record(await api<unknown>(`/admin/v1/cases/${encodeURIComponent(selected.id)}/review`, { method: 'POST', headers, body: JSON.stringify(body) })); const changed = caseOf(data.case ?? data); if (changed) setSelected(changed); setNotice(`案件 ${selected.caseCode} 已更新為「${review.label}」。`); await load(); } catch (e) { const err = e as ApiError; setPanelError(err.status === 409 ? '此案件已被更新，請重新整理後檢查最新狀態。' : err.message); } finally { setBusy(false); } };
  if (view === 'login') return <Login busy={busy} error={authError} submit={login} forgot={() => { setAuthError(''); setView('recovery'); }} />;
  if (view === 'recovery') return <Recovery busy={busy} error={authError} start={start} complete={complete} back={() => { setAuthError(''); setView('login'); }} />;
  if (view === 'password') return <PasswordChange forced={session?.mustChangePassword === true} busy={busy} error={authError} save={change} back={() => setView('dashboard')} />;
  return <div className="shell"><a className="skip" href="#main">跳到主要內容</a><header className="top"><a className="brand" href="#main" onClick={() => { setManaging(null); setView('dashboard'); }}><b>FP</b><strong>FlowPass</strong><small>管理後台</small></a><nav className="top-nav" aria-label="管理後台"><span>{session?.displayName ?? '管理員'}</span>{view === 'dashboard' && <><button className="link" onClick={() => { setAuthError(''); setView('ai-usage'); }}>AI 用量</button><button className="link" onClick={() => { setAuthError(''); setView('security-incidents'); }}>資安提醒</button></>}<button className="link" onClick={() => { setAuthError(''); setView('password'); }}>變更密碼</button><button className="link" onClick={() => void logout()} disabled={busy}>登出</button></nav></header>{notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice('')} aria-label="關閉通知">×</button></div>}<main id="main">{view === 'ai-usage' ? <AiUsagePanel request={api} onBack={() => setView('dashboard')} /> : view === 'security-incidents' ? <SecurityAlertPublisher request={api} onBack={() => setView('dashboard')} /> : managing ? <DataManager caseId={managing.id} caseCode={managing.caseCode} request={api} onBack={() => setManaging(null)} onDeleted={(result) => { setManaging(null); setSelected(null); setNotice(`案件 ${result.caseCode} 及其全部相關資料已永久刪除。`); void load(); }} /> : loading && !cases.length && !queueError ? <div className="loading" role="status">正在載入案件資料…</div> : <Queue cases={cases} selected={selected} select={setSelected} manage={(item) => { setSelected(null); setManaging(item); }} refresh={() => void load()} refreshing={loading} loadError={queueError} onRetry={() => void load()} />}</main>{!managing && selected && <div className="layer"><button className="backdrop" onClick={() => setSelected(null)} aria-label="關閉案件詳情" /><Panel key={`${selected.id}:${selected.state}:${selected.rowVersion ?? ''}`} item={selected} busy={busy} error={panelError} close={() => setSelected(null)} clearError={() => setPanelError('')} update={update} /></div>}</div>;
}
createRoot(document.getElementById('root')!).render(<App />);
