import { ApiErrorCode, apiFailure, apiSuccess, parseQuotedEtag, toJsonResponse } from '../../../../../../shared/api-contract';
import { getPublicRuntime } from '../../../../../../server/public/runtime';
import { isValidMutationKey, readApplicantMutation, reserveApplicantMutation, finalizeApplicantMutation, deleteApplicantMutationReservation } from '../../../../../../server/public/public-mutations';
import { taskCompletionAllowed, taskCompletionEvent, validateTaskAction } from '../../../../../../server/domain/task-service';
import { appendEncryptedAuditLog } from '../../../../../../server/db/repositories/audit';
import { v7 as uuidv7 } from 'uuid';
function cookie(request: Request, name: string): string | null { for (const part of (request.headers.get('cookie') ?? '').split(';')) { const [key, ...value] = part.trim().split('='); if (key === name) return value.join('=') || null; } return null; }
export async function POST(request: Request, context: { params: Promise<{ taskId: string }> }): Promise<Response> {
  const runtime = getPublicRuntime(); const requestId = runtime?.requestIdGenerator?.() ?? crypto.randomUUID();
  if (!runtime) return toJsonResponse(apiFailure(ApiErrorCode.DEPENDENCY_UNAVAILABLE, requestId));
  if (!runtime.lineSessions.isPublicOrigin(request.headers.get('origin'))) return toJsonResponse(apiFailure(ApiErrorCode.CSRF_FAILED, requestId));
  const sessionToken = cookie(request, 'flowpass_session'); const csrf = runtime.lineSessions.verifyApplicantCsrf({ sessionToken, csrfCookie: cookie(request, 'flowpass_csrf'), csrfHeader: request.headers.get('x-flowpass-csrf') }); const key = request.headers.get('idempotency-key'); const expected = parseQuotedEtag(request.headers.get('if-match'));
  if (!csrf) return toJsonResponse(apiFailure(ApiErrorCode.CSRF_FAILED, requestId)); if (!isValidMutationKey(key) || expected === null) return toJsonResponse(apiFailure(ApiErrorCode.INVALID_REQUEST, requestId));
  const { taskId } = await context.params; let body: unknown; try { body = await request.json(); } catch { return toJsonResponse(apiFailure(ApiErrorCode.INVALID_REQUEST, requestId)); } const action = body && typeof body === 'object' && typeof (body as Record<string, unknown>).action === 'string' ? (body as { action: string }).action : undefined; if (!action) return toJsonResponse(apiFailure(ApiErrorCode.INVALID_REQUEST, requestId));
  const now = runtime.clock?.() ?? new Date(); const route = `/api/v1/tasks/${taskId}/complete`; const projection = { taskId, ifMatch: request.headers.get('if-match'), action }; const existing = readApplicantMutation({ database: runtime.database, crypto: runtime.crypto, applicantId: csrf.applicantId, method: 'POST', normalizedRoute: route, idempotencyKey: key, requestProjection: projection, now });
  if (existing?.kind === 'replay') return toJsonResponse(JSON.parse(existing.body), { status: existing.status }); if (existing?.kind === 'conflict') return toJsonResponse(apiFailure(ApiErrorCode.IDEMPOTENCY_KEY_REUSED, requestId)); const reservation = reserveApplicantMutation({ database: runtime.database, crypto: runtime.crypto, applicantId: csrf.applicantId, method: 'POST', normalizedRoute: route, idempotencyKey: key, requestProjection: projection, now }); if (reservation.kind !== 'reserved') return toJsonResponse(apiFailure(ApiErrorCode.IDEMPOTENCY_KEY_REUSED, requestId));
  try {
    const data = runtime.database.transaction(() => {
      const row = runtime.database.prepare(`SELECT t.*, c.state AS case_state, c.row_version AS case_row_version FROM case_tasks t JOIN cases c ON c.id = t.case_id WHERE t.id = ? AND c.applicant_id = ?`).get(taskId, csrf.applicantId) as { id: string; case_id: string; task_type: string; status: string; due_at: string | null; row_version: number; case_state: string; case_row_version: number } | undefined;
      if (!row) throw new Error('NOT_FOUND'); if (row.row_version !== expected) throw new Error('ETAG_MISMATCH'); validateTaskAction(row.task_type, action); if (!taskCompletionAllowed({ status: row.status as never, dueAt: row.due_at }, now.toISOString())) throw new Error('INVALID_STATE');
      const changed = runtime.database.prepare(`UPDATE case_tasks SET status = 'completed', completed_at = ?, row_version = row_version + 1 WHERE id = ? AND row_version = ? AND status IN ('open','opened')`).run(now.toISOString(), taskId, expected); if (changed.changes !== 1) throw new Error('INVALID_STATE'); const nextCaseState = row.task_type === 'provide_document' || row.task_type === 'revise_passport' ? 'resubmitted' : row.case_state; const caseChanged = runtime.database.prepare('UPDATE cases SET state = ?, row_version = row_version + 1, updated_at = ? WHERE id = ? AND row_version = ?').run(nextCaseState, now.toISOString(), row.case_id, row.case_row_version); if (caseChanged.changes !== 1) throw new Error('ETAG_MISMATCH'); runtime.database.prepare(`INSERT INTO timeline_events (id, case_id, sequence_no, passport_version_id, event_type, public_summary, public_data_json, actor_type, created_at) VALUES (?, ?, (SELECT COALESCE(MAX(sequence_no), 0) + 1 FROM timeline_events WHERE case_id = ?), NULL, ?, ?, ?, 'applicant', ?)`).run(uuidv7(), row.case_id, row.case_id, taskCompletionEvent(row.task_type), '待辦事項已完成', JSON.stringify({ status: 'completed' }), now.toISOString()); appendEncryptedAuditLog(runtime.database, runtime.crypto, { id: uuidv7(), actorType: 'applicant', actorId: csrf.applicantId, action: 'update', entityType: 'case_task', entityId: taskId, beforeHash: null, afterHash: null, detail: { kind: 'operation', operation: 'update', outcome: 'ok' }, requestId, createdAt: now.toISOString() }); return { taskId, taskType: row.task_type, status: 'completed', completedAt: now.toISOString(), rowVersion: expected + 1 };
    })(); const response = apiSuccess(data, requestId, data.rowVersion); if (!finalizeApplicantMutation({ database: runtime.database, crypto: runtime.crypto, reservation, idempotencyKey: key, status: 200, publicBody: JSON.stringify(response), now })) throw new Error('DEPENDENCY_UNAVAILABLE'); return toJsonResponse(response, { status: 200, headers: { ETag: response.meta.etag ?? '', 'Cache-Control': 'no-store' } });
  } catch (error) { deleteApplicantMutationReservation({ database: runtime.database, crypto: runtime.crypto, reservation, idempotencyKey: key }); const message = error instanceof Error ? error.message : ''; const code = message === 'NOT_FOUND' ? ApiErrorCode.NOT_FOUND : message === 'ETAG_MISMATCH' ? ApiErrorCode.ETAG_MISMATCH : message === 'INVALID_STATE' || message === 'INVALID_ACTION' ? ApiErrorCode.INVALID_STATE : ApiErrorCode.DEPENDENCY_UNAVAILABLE; return toJsonResponse(apiFailure(code, requestId)); }
}
